[package]
name = "dbclient"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.25"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.0", features = ["derive"] }
toml = "0.8.23"

#db clients
redis = { version = "0.31"}

