use std::fmt::Write;

use prost_build::{Service, ServiceGenerator};

/// Generates a small, transport-agnostic async trait for every protobuf service.
///
/// The request and response types are the message types generated by `prost`.
/// Transport concerns (HTTP, gRPC, an in-process dispatcher, etc.) stay outside
/// of the generated API.
#[derive(Default)]
struct AsyncServiceGenerator;

impl ServiceGenerator for AsyncServiceGenerator {
    fn generate(&mut self, service: Service, buf: &mut String) {
        service.comments.append_with_indent(0, buf);
        buf.push_str("#[allow(async_fn_in_trait)]\n");
        buf.push_str("#[::async_trait::async_trait]\n");
        writeln!(buf, "pub trait {} {{", service.name).unwrap();

        for method in service.methods {
            method.comments.append_with_indent(1, buf);
            writeln!(
                buf,
                "    async fn {}(&self, request: {}) -> ::anyhow::Result<{}>;",
                method.name, method.input_type, method.output_type
            )
            .unwrap();
        }

        buf.push_str("}\n");
    }
}

pub fn configure() -> prost_build::Config {
    let mut config = prost_build::Config::new();
    config.service_generator(Box::new(AsyncServiceGenerator));
    config
}
