name: Tag master

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Create tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')
          if [[ -z "$VERSION" ]]; then
              echo "VERSION is empty"
              exit -1
          fi
          TAG="v$VERSION"

          gh api \
            --method POST \
            "/repos/${{ github.repository }}/git/refs" \
            -f ref="refs/tags/$TAG" \
            -f sha="${{ github.sha }}"
